### ISSUE TITLE
Rux vs Erb benchmarks 

### ISSUE THREAD

**Issue by serhiihiba** [camertron/rux-rails#13]
Are there any benchmarks available that compare the render speed of Rux vs ERB templates? Additionally, how does rendering time increase by increasing deeply nested components?

**Comment by camertron** [comment]
There are currently no benchmarks, although [this issue](https://github.com/camertron/rux-rails/issues/5) seems to suggest rux is 3-5x slower than Slim. The view_component repo contains a [few benchmarks](https://github.com/ViewComponent/view_component/tree/main/performance), and so does [phlex](https://github.com/phlex-ruby/phlex/blob/main/bench.rb). I'll see if I can put together a couple of rux benchmarks.

**Comment by camertron** [comment]
Here we go: https://github.com/camertron/rux-rails/pull/14

It looks like Slim is actually _slower_ than rux?? I must be doing something wrong here?

**Comment by serhiihiba** [comment]
Maybe Rux really fast 🙃
