### ISSUE TITLE
transpilling not happening automatically in development

### ISSUE THREAD

**Issue by luizkowalski** [camertron/rux-rails#2]
Hi,
First of all, great work on this project! I truly believe this is a game-changer. Now, to the issue :D 

I have the following line on a HAML file:

```ruby
= render(FlagsComponent.new(first_name: 'Luiz'))
```

and this is my component:

```ruby
class FlagsComponent < ViewComponent::Base
  def initialize(first_name:)
    @first_name = first_name
  end

  def call
    ...
  end
end
```

When I run it (in development) I get the following error:

`uninitialized constant FlagsComponent`

I manually transpilled my component with `bundle exec rake rux:transpile`, got a new `flags_component.rb` and now the view is working fine.

Apparently, transpilling on development is not happening.

I'm using Rails 6.1.3.2 on Ruby 3.0.1 (Mac OS)

**Comment by camertron** [comment]
Hey @luizkowalski, thanks for the kudos, and for the bug report :)

I wasn't able to reproduce your issue using the same ruby and rails versions, although I did find a bug related to ruby 3's new handling of keyword arguments. Might be related to what you're seeing? I just released rux v1.0.2 to fix the problem. Try running `bundle update --source rux` to pull in the new version.

A couple of other things to try:
1. I specifically tested this and didn't run into any problems, but I wonder if spring is getting in your way? What happens if you run `spring stop` and try requesting the page again?
1. Is your component in the app/components directory? I wonder if rux (or maybe rails) is having trouble finding it because it's in a non-standard location.
1. If you're still running into problems, please push up a minimal rails app that reproduces the problem and post the link here. I'd be happy to take a look.

**Comment by luizkowalski** [comment]
I updated to no luck yet but here are my founds:

1. When I access Rails' console and type `Rux.library_paths` I get an empty array
2. I added `Rux.library_paths << "#{config.root}/app/components/"` to my `application.rb` file, also no luck

Answering your questions:

1. I'm not using spring
2. Yes, the components are under `app/components` dir
3. I can do that but maybe the problem is in my app, some gem, some config that maybe is screwing it all up and I'd like to first exhaust my options here since you can't reproduce it.

Maybe it has to do with the fact that I'm trying to use `render` inside a `haml` file? I noticed in your `dummy` app on tests, you have a `ruxt` file instead `html` or `erb`...does that make sense?

**Comment by luizkowalski** [comment]
oh, one more thing: if I access the console again and type `require './app/components/my_component.rux'` for example, it raises an error (`NoMethodError: undefined method 'autoloads' for nil:NilClass)` but actually transpilles the file and creates a `my_component.rb`

**Comment by camertron** [comment]
@luizkowalski ok thanks for the additional info. The `library_path` is only for external libraries like gems, etc, so it probably isn't the problem.

Based on that `NoMethodError` you're getting, it looks like app/components isn't on rails' eager load paths. What output do you get if you run `Rails.application.config.eager_load_paths` in a rails console?

Another thing to check is the return value of:

```ruby
Zeitwerk::Registry.loader_for(Rails.root.join('app', 'components', 'flags_component.rux').to_s)
```

**Comment by luizkowalski** [comment]
this is what I see when I run `Rails.application.config.eager_load_paths`:

```shell
[1] pry(main)> Rails.application.config.eager_load_paths
=> ["/Users/luiz/rails_dev/name/app/business_concerns",
 "/Users/luiz/rails_dev/name/app/components",
```

When I run the second command, this is what I get:

```shell
[2] pry(main)> Zeitwerk::Registry.loader_for(Rails.root.join('app', 'components', 'flags_component.rux').to_s)
=> nil
```

The thing is: I'm not using Zeitwerk...could this be related? I noticed now that the gem relies on Zeitwerk

**Comment by camertron** [comment]
@luizkowalski aha now we're getting somewhere! Rux-rails hooks into either Zeitwerk or `ActiveSupport::Dependencies`, whichever one your app uses. It tries to `require 'zeitwerk'`, and if that fails, falls back to `AS::Dependencies`. Do you have the zeitwerk gem in your Gemfile? If so, try removing it.

**Comment by camertron** [comment]
I just realized rux-rails should probably be looking at the value of `Rails.application.config.autoloader` too. Let me see what I can do to fix that.

**Comment by luizkowalski** [comment]
there we go, I think we found it. yeah, I do have `zeitwerk` on my gemfile.lock actually, some other gem requires it but I'm not using it...I actually opened a PR on my project, migrating to `zetiwerk` so this issue should go away but I believe we found the problem here

**Comment by camertron** [comment]
@luizkowalski ok, v1.2.0 of rux-rails moves the monkeypatching stuff into the railtie, meaning it can examine the value of `config.autoloader` and choose the right patches to load. In other words, if your Gemfile contains zeitwerk but `config.autoloader` is set to `:classic`, the right (classic) patch gets loaded. Would you mind giving it a try?

**Comment by luizkowalski** [comment]
That's it, working like a charm now 😄 

That solves the issue, I think this can be closed. Thank you for this! ❤️

**Comment by camertron** [comment]
Excellent!! Thanks for testing it out :)
