### ISSUE TITLE
Is there any support for namespaced View Components?

### ISSUE THREAD

**Issue by stwr667** [camertron/rux-rails#3]
Love the idea of this @camertron! Do you plan to make it work with ruby namespaces?

E.g. we currently render a ViewComponent with:
```erb
<%= render UserAssignment::AvailableUsersComponent.new(users: @my_users) %>
```
But it doesn't look like this works:
```
<UserAssignment::AvailableUsersComponent users={@my_users} />
```
We get this error:
```
ActionView::Template::Error (no transition found from tRUX_TAG_OPEN_TEST at position 254 while lexing rux code):

rux (1.0.3) lib/rux/rux_lexer.rb:112:in `block in each_rux_token'
rux (1.0.3) lib/rux/rux_lexer.rb:105:in `loop'
rux (1.0.3) lib/rux/rux_lexer.rb:105:in `each_rux_token'
rux (1.0.3) lib/rux/rux_lexer.rb:70:in `each_token'
```

**Comment by stwr667** [comment]
My bad, closing as a non-issue. The above actually works.
I got the error because there were other `<%` and `%>` tags left in my `.ruxt` file, and I thought they would still be supported. But after converting them to `{` and `}`, it works.

**Comment by camertron** [comment]
Hey @stwr667, glad you got things working! Rux _should_ support namespaced component classes :)
