### ISSUE TITLE
Uninitialized constant error when calling component defined in `.rux` file from view

### ISSUE THREAD

**Issue by stefcoetzee** [camertron/rux-rails#4]
## Steps to reproduce

Clone the [example repo](https://github.com/stefcoetzee/view-component-rux), run `bin/dev`, and visit `localhost:3000`.

## Expected behavior

Show view containing generated instance of `NameComponent` class ([provided on the gem's GitHub page](https://github.com/camertron/rux-rails#writing-rux-components)).

## Actual behavior

When attempting to use the `NameComponent` class, I run into an `uninitialized constant` error. This is raised from `./app/views/home/index.html.erb` where a `render` call to `NameComponent` is made:

```erb
<%= render(NameComponent.new(first_name: "Joe", last_name: "Example")) %>
```

If I run `bundle exec ruxc app/components/name_component.rux` to generate `./app/components/name_component.rb` and reload, an `uninitialized constant NameComponent` error is raised from `./app/views/home/index.html.erb`.

If something nonsensical (e.g. `.foo`) is appended to the `.rux` file to make it unrecognizable to `rux-rails`, the component works as expected.

## System configuration

Ruby version: 3.0.1
Rails version: 7.0.1
Gem version: 1.2.0

Note that the application uses Postgres and Tailwind CSS.

## Unclear how to fix it

I'm not sure which steps I'm missing in my implementation of `rux-rails` above. The generated component does work once the `.rux` file is taken out of the picture, which makes me wonder if it's something to do with the transpilation step.

Thanks @camertron, for sharing this gem with the community. :)

**Comment by camertron** [comment]
Hey @stefcoetzee, thanks for the detailed bug report :) I was able to reproduce the problem in one of my test beds (and in your example repo as well). Everything still seems to work ok in Rails 6.1, so I think Rails 7 is to blame. It also looks like there are some recent changes to Zeitwerk that are causing v2.5 to raise errors in Rails 6.1. Unfortunately getting Ruby/Rails to autoload .rux files was always a bit hacky. I'll need to dig in further.

**Comment by camertron** [comment]
Ok I was able to track down the issue and fix it. Everything should work in v1.2.1 :)
