### ISSUE TITLE
Tailwindcss

### ISSUE THREAD

**Issue by serhiihiba** [camertron/rux-rails#6]
I'm not sure about using tailwindcss with rux, can you show little example, please?

**Comment by camertron** [comment]
Hey @serhiijun good question. Unfortunately I've never used Tailwind and don't understand how it works. All I know is that it's a bunch of utility classes. Isn't it just a matter of adding those classes to whatever HTML element you want them on? Eg:

```ruby
class MyComponent < ViewComponent::Base
  def call
    <button class="h-10 px-6 font-semibold rounded-md bg-black text-white">
      Click Me
    </button>
  end
end
```
